# Generated by Django 5.0.4 on 2024-07-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processeddata',
            name='total_sales',
        ),
        migrations.AddField(
            model_name='processeddata',
            name='daily_total_sales',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='processeddata',
            name='total_sales_by_product',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='store_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='top_selling_product',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='product_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='store_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='total_sales',
            field=models.FloatField(),
        ),
    ]
