# Generated by Django 5.0.4 on 2024-07-11 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_processeddata_daily_total_sales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processeddata',
            name='top_selling_product',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='product_id',
            field=models.CharField(max_length=30),
        ),
    ]
